In [3]:
import mymatrixmodule as matrix

In [4]:
A = [[1,3,7],
     [5,8,-9],
     [6,-7,1]]

B = [[2,3,5],
     [5,-9,-9],
     [6,8,1]]

In [6]:
c = matrix.matrixaddition(A,B)
print(c)

[[3, 6, 12], [10, -1, -18], [12, 1, 2]]


In [7]:
c = matrix.matrixsubtraction(A,B)
print(c)

[[-1, 0, 2], [0, 17, 0], [0, -15, 0]]


In [8]:
c = matrix.matrixmultiplication(A,B)
print(c)

[[59, 32, -15], [-4, -129, -56], [-17, 89, 94]]


In [9]:
import numpy as np

In [11]:
d = np.dot(A,B)
print(d)

[[  59   32  -15]
 [  -4 -129  -56]
 [ -17   89   94]]
