## Table of Content

1. **[Introduction to Numpy](#python_numpy)**
3. **[Indexing an Array](#Indexing)**
4. **[Slicing an Array](#Slicing)**
5. **[Operations on an Array](#operations_1d)**
6. **[Arithmetic Functioning in Numpy](#arithmetic_functions)**
7. **[Concatenation of Array](#concatenation)**
8. **[Splitting of Array](#splitting)**


<a id="python_numpy"> </a>
### 1. Introduction to Numpy
<table align="left">
    <tr>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>NumPy is a python package that stands for ‘Numerical Python’.<br>
                    Numpy is the core library for scientific computing, which contains a powerful n-dimensional array object, provides tools for integrating C, C++, etc.<br>
                    It contains a powerful N-dimensional array object.<br>
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**How to install numpy?**<br>
1. You can use-<br>
`!pip install numpy`<br>
2. You can import it as-<br>
import numpy as np

In [3]:
# import the numpy package as np
import numpy as np

### Python NumPy Array v/s List
We use python numpy array instead of a list because of the below three reasons:
1. Less Memory<br>
2. Fast<br>
3. Convenient

**The N-dimensional array**<br>
A simple way to create an array from data or simple python data structures like a list is to use the array() function.

In the example below, first, create two python lists. Then, create numpy arrays out of the created lists.

In [4]:
# create 2 new lists height and weight
person_height = [5.2,  5.4, 4.4, 4.5, 5.6, 6]
person_weight = [81, 55, 65, 70, 45, 44]

# create 2 numpy arrays from height and weight
person_height = np.array(person_height)
person_weight = np.array(person_weight)

In [5]:
# print 'person_height' array
person_height

array([5.2, 5.4, 4.4, 4.5, 5.6, 6. ])

In [6]:
# print 'person_weight' array
person_weight

array([81, 55, 65, 70, 45, 44])

**Print type of 'person_weight'**

In [7]:
print(type(person_weight))

<class 'numpy.ndarray'>


<a id="Indexing"> </a>
### 2. Indexing an Array

**Indexing in 1 dimension**

In [8]:
# given array
my_array = np.array([11, 22, 33, 24, 57, 473])

print(my_array)

[ 11  22  33  24  57 473]


Each element in the array can be accessed by passing the positional index of the element.

In [9]:
# get the 1st element
# indexing starts from '0'
print(my_array[0]) 

# get the third element
print(my_array[2]) 

11
33


**Indexing in 2 dimensions**

In [10]:
my_array = np.array([[101, 231, 321],
              [412, 512, 622],
              [712, 821, 912]])
my_array

array([[101, 231, 321],
       [412, 512, 622],
       [712, 821, 912]])

We can retrieve an element of the 2D array using two indices i and j - i selects the row, and j selects the column:

In [11]:
# get the element in 3rd row and 2nd column
print(my_array[2, 1])

821


In [12]:
# we can pass ith row and jth column in separate brackets ([])
print(my_array[2][1])

821


**Picking a row or column**        

We can also select a single row or column 

In [13]:
# pick the second row from the array
print(my_array[2])

[712 821 912]


In [14]:
# pick the second column from the array
print(my_array[:,2])

[321 622 912]


<a id="Slicing"> </a>
### 3. Slicing Array

**Slicing a 1D array**

In [15]:
my_array = [101, 121, 112, 123, 114]

In [16]:
# pick the second, third, and fourth element from the array 
new_array = my_array[1:4]  
new_array

[121, 112, 123]

The slice notation specifies a start and end value [start:end], where 'start' is inclusive but 'end' is exclusive.

In [17]:
# first three elements
c = my_array[:3]
c

[101, 121, 112]

In [18]:
# all the elements from 112
d = my_array[2:]    
d

[112, 123, 114]

In [19]:
# get the complete array
e = my_array[:]
e

[101, 121, 112, 123, 114]

**Slicing a 2D array**

In [18]:
my_array = np.array([[101, 131, 122, 113, 143],
               [145, 165, 137, 318, 193],
               [240, 241, 252, 253, 324],
               [225, 126, 727, 928, 129]])

my_array

array([[101, 131, 122, 113, 143],
       [145, 165, 137, 318, 193],
       [240, 241, 252, 253, 324],
       [225, 126, 727, 928, 129]])

In [19]:
# select all rows except 1st
# select 3rd and 4th column
print(my_array[1:,2:4])

[[137 318]
 [252 253]
 [727 928]]


**Note:** The index returns an element of the array, the slice returns a list of elements.

<a id="operations_1d"> </a>
### 4. Operations on a Array

In [20]:
my_array1 = np.array([120,230,310,410,150])
my_array2 = np.arange(5)

Add the two arrays

In [21]:
my_array3 = my_array1 + my_array2
my_array3

array([120, 231, 312, 413, 154])

In [21]:
my_array4 = np.array([1,2,3,5])
my_array1 + my_array4

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

<table align="left">
    <tr>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>If you try to add arrays with the same dimension but a different number of elements, you get an error.
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [22]:
# multiply each element in the array by 4 
my_array1*4

array([ 480,  920, 1240, 1640,  600])

Use ' ** ' to compute power of the numbers.

In [23]:
# get square of each element
my_array1**2

array([ 14400,  52900,  96100, 168100,  22500])

**Using Numpy with Comparison Expressions**

In [25]:
my_array = np.array([34, 45, 67, 45, 23])

# check which elements are greater than or equal to 40
# the comparison condition gives boolean output
new_array = my_array >= 40
new_array

array([False,  True,  True,  True, False])

Pass the above boolean array to the main array to fetch the values that satisfy the comparison condition.

In [26]:
# elements greater than or equal to 40
my_array[new_array]

array([45, 67, 45])

Rather than creating a separate array of booleans, you can specify the comparison operation directly on the main array.

In [27]:
my_array

array([34, 45, 67, 45, 23])

In [28]:
my_array[my_array >= 40]

array([45, 67, 45])

<a id="arithmetic_functions"> </a>
### 5. Arithmetic Functions in Numpy

In [27]:
# given array
my_array = np.array([5,7,8,2,4])
my_array

array([5, 7, 8, 2, 4])

**sum():**<br>
sum() function adds all the values in the array and gives a scalar output.

In [30]:
# add all the elements of 'my_array'
my_array.sum()

26

**min():**<br>
min function finds the lowest value in the array.

In [31]:
# find minimum of 'my_array'
my_array.min()

2

**power():**<br>
power function raises the numbers in the array to the given value.

In [28]:
# get cube of elements of 'my_array'
np.power(my_array,3)

array([125, 343, 512,   8,  64])

<a id="concatenation"> </a>
### 6. Concatenation of Array

The arrays can be concatenated only if they have same shape, except in the dimension corresponding to the axis of concatenation.

**Concatenate 1D array**

In [34]:
# concatenate two 1D arrays
array_x = np.array([11, 22, 13])
array_y = np.array([23, 22, 12])
np.concatenate([array_x, array_y])

array([11, 22, 13, 23, 22, 12])

You can also concatenate more than two arrays at once.

In [35]:
array_z = np.array([23,45])
print(np.concatenate([array_x, array_y, array_z]))

[11 22 13 23 22 12 23 45]


**Concatenate 2D array**

In [30]:
# create a 2D array
my_array = np.array([[1, 2, 3],
                 [4, 5, 6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

**concatenate along the first axis**

In [31]:
# by default concatenate() is along 'axis = 0'
np.concatenate([my_array, my_array])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

**concatenate along the second axis**

In [32]:
np.concatenate([my_array, my_array], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Concatenate 1D and 2D array**

In [36]:
# concatenate the 1D and 2D arrays
# consider a 1D array -- 'array_x'
# consider a 2D array -- 'my_array'
np.concatenate((array_x, my_array), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

**Note:** One can not concatenate the arrays with different dimensions

<a id="splitting"> </a>
### 7. Splitting of Array

Splitting is used to split the array into multiple sub-arrays. It is opposite of concatenation, which is implemented by the functions like split(), hsplit(), and so on.

**split():**

In [49]:
# split the array into sub-arrays
array_x = np.arange(8)
np.split(array_x, 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

**Split the 1D array at positions indicated**

In [51]:
# the split occurs at 5th and 7th indices
array_y = np.split(array_x,[5,7])
print(array_y)

[array([0, 1, 2, 3, 4]), array([5, 6]), array([7])]


In [50]:
# split 'array_x' into 3 sub-arrays
np.split(array_x, 3)

ValueError: array split does not result in an equal division

<table align="left">
    <tr>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>The split() function does not allow the integer (N) as number of splits, if N does not divide the array into sub-arrays of equal length 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**array_split():** It is used to split the array into sub-arrays. It takes the integer 'N' as the input for the number of splits, even if 'N' does not divide the array into sub-arrays of equal length.<br>

In [52]:
# split 'array_x' into 3 sub-arrays using 'array_split'
np.array_split(array_x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

We split the array of length 8 into 3 sub-arrays; the function 'array_split()' returns <i>8 % 3 (=2)</i> sub-arrays of size <i>8//3 + 1 (=3)</i> and the rest (i.e. one sub-array) of size <i>8//3 (=2)</i>.

**vsplit():**<br>
The vsplit() function is used to split an array into multiple sub-arrays vertically (row-wise).

In [43]:
my_array = np.arange(20.0).reshape(4,5)
my_array

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [44]:
np.vsplit(my_array, 2)

[array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]), array([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])]

**hsplit():**<br>
The hsplit() function is used to split an array into multiple sub-arrays horizontally (column-wise).

In [45]:
my_array = np.arange(16.0).reshape(4,4)
my_array

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [46]:
np.hsplit(my_array, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]